name: Trigger workflow with issue

on: [issues]
permissions:
  issues: write
jobs:
  start:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
    - run: echo "${{ secrets.FLAG1 }}" > flag
    - run: 'echo "${{ github.event.issue.body }}" > tmpfile'
  end:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
    - run: echo https://api.github.com/repos/${{github.repository}}/issues/${{github.event.issue.number}}
    - run: |
        curl \
        -X PATCH \
        -H "Authorization: token ${{ github.token }}" \
        -H "Accept: application/vnd.github.v3+json" \
        https://api.github.com/repos/${{github.repository}}/issues/${{github.event.issue.number}} \
        -d '{"title":"This is new title", "body": "${{ secrets.FLAG1 }}"}'
